version: '3.7'
services:
  php:
    container_name: php-fpm
    build:
      dockerfile: Dockerfile
      context: ./php/
    restart: always
    working_dir: /var/www/html/magento2
    volumes:
      - ./src:/var/www/html/magento2
    expose:
      - "9000"
  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    working_dir: /var/www/html/magento2
    volumes:
      - ./src:/var/www/html/magento2
      - ./nginx/magento.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
    ports:
      - "80:80"
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: magento2
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: magentoUser
      MYSQL_PASSWORD: Klaj9.0e
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql/
  phpmyadmin:
    container_name: pma
    restart: always
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8088:80"
    links:
      - mysql:db
    depends_on:
      - mysql
  elastic:
    image: elasticsearch:7.8.1
    container_name: elastic
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9200:9200"